# Generated by Django 3.2.8 on 2021-11-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=127, null=True)),
                ('text', models.TextField(help_text='Bura esas melumati daxil edin...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=63, verbose_name='Muellif')),
                ('cats', models.IntegerField(choices=[(2, 'fashion'), (1, 'sport'), (4, 'politics'), (3, 'technology')], default=1, max_length=100)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ('created_at',),
            },
        ),
    ]
