# Generated by Django 3.2.8 on 2021-11-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=63, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='cats',
            field=models.IntegerField(choices=[(4, 'politics'), (3, 'technology'), (2, 'fashion'), (1, 'sport')], default=1, max_length=100),
        ),
    ]
