# Generated by Django 3.2.8 on 2021-11-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211101_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cats',
            field=models.IntegerField(choices=[(1, 'sport'), (3, 'technology'), (2, 'fashion'), (4, 'politics')], default=1, max_length=100),
        ),
    ]
