# Generated by Django 3.2.8 on 2021-11-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211101_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cats',
            field=models.IntegerField(choices=[(1, 'sport'), (2, 'fashion'), (4, 'politics'), (3, 'technology')], default=1, max_length=100),
        ),
    ]
