# Generated by Django 3.2.8 on 2021-11-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211102_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cats',
            field=models.IntegerField(choices=[(1, 'sport'), (2, 'fashion'), (3, 'technology'), (4, 'politics')], default=1, max_length=100),
        ),
    ]
