# Generated by Django 3.2.8 on 2021-11-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_cats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cats',
            field=models.IntegerField(choices=[(3, 'technology'), (1, 'sport'), (2, 'fashion'), (4, 'politics')], default=1, max_length=100),
        ),
    ]
