# Generated by Django 3.2.8 on 2021-11-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_cats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cats',
            field=models.IntegerField(choices=[(4, 'politics'), (2, 'fashion'), (3, 'technology'), (1, 'sport')], default=1, max_length=100),
        ),
    ]
