# Generated by Django 3.2.8 on 2021-11-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_cats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cats',
            field=models.IntegerField(choices=[(1, 'sport'), (3, 'technology'), (4, 'politics'), (2, 'fashion')], default=1, max_length=100),
        ),
    ]
