# Generated by Django 3.2.8 on 2021-11-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=127, null=True)),
                ('email', models.TextField(help_text='Bura emailinizi daxil edin...')),
                ('confPassword', models.CharField(max_length=63, verbose_name='Muellif')),
            ],
        ),
    ]
